version: '3'
services:
  api:
    container_name: api
    restart: always
    build: .
    # ports:
    #   - '80:8000'
    networks:
      - face-sentiment
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - face-sentiment
networks:
  face-sentiment:
    external: true
