version: '3'
services:
  app:
    container_name: faces_api
    restart: always
    build: .
    ports:
      - '8888:3000'
    networks:
      - face-sentiment
networks:
  face-sentiment:
    external: true
